default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV["DB_PASSWORD"] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: github-action-ruby_development

test:
  <<: *default
  database: github-action-ruby_test

production:
  <<: *default
  database: github-action-ruby_production
  username: github-action-ruby
  password: <%= ENV['GITHUB-ACTION-RUBY_DATABASE_PASSWORD'] %>
